### PR TITLE
Include MTIDD Dependency

### PR DESCRIPTION
**Pull request by AntonXue**
---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal3/346)

### CODE REVIEW

**Comment by soonho-tri** [comment]
I'm checking the linux/mac builds now. 

BTW, how about making a `mtidd` directory under `src/tests` and add a simple test using `mtidd`? You can find an example at https://github.com/dreal/dreal3/tree/master/src/tests/capd4.

**Comment by soonho-tri** [comment]
@AntonXue , it works on Linux but not on Mac:
```
cp: libmtidd.so: No such file or directory
```
Because on OSX, we have `external/src/MTIDD/libmtidd.dylib`, not `libmtidd.so`.

**Comment by AntonXue** [comment]
This is a really whack fix, but if I change `cp libmtidd.do` to `cp mtidd.*` it appears to work on my machine. Would this be an acceptable change for Mac compatibility, or are there better alternatives?

**Comment by soonho-tri** [comment]
Please try:

```
CONFIGURE_COMMAND ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_BINARY_DIR}/external/src/MTIDD/src

...
INSTALL_COMMAND make install)

I think this is the right approach. However https://github.com/dzufferey/mtidd/blob/master/src/CMakeLists.txt#L77-L81 should be updated because for now it installs the `.h` files under `<PREFIX>/include/src` instead of `<PREFIX>/include/mtidd`.

**Comment by AntonXue** [comment]
Made changes to `dreal`'s `src/CMakeList.txt` and also changed `mtidd`'s `src/CMakeList.txt`.

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal3/346#-:-Ko7yatbTycPA9NdCU_e:bnfp4nl)*

**Pull request merged**
