### PR TITLE
Fixed rebase for networks of automata

### PR DESCRIPTION
**Pull request by danbryce**

### CODE REVIEW

**Comment by soonhokong** [comment]
Closed by fae153a4995e97db7e03077ae4f42c36778f38a9

**Comment by soonhokong** [comment]
@danbryce, after merging those commits I found that models under `benchmakrs/hybrid_systems` are not working anymore. Here is a repro step:

```bash
cd benchmarks/hybrid_systems/bouncing_ball
make
```

For now, it generates the following errors:
```
../../../bin/dReach -k 3 bouncing_ball.drh --precision=0.01 --ode_grid=1024 --visualize
dReal Options: --precision=0.01 --ode_grid=1024 --visualize
/usr0/home/soonhok/work/dreal3/bin/bmc: Path (set-logic is not well-formed.
Usage: main.native [<options>] <.drh>
<options> are:
  -k : number of unrolling (Default: 3)
  --pathgen : generate paths
  --bmc_heuristic : generate BMC heuristic for dReal
  --bmc_heuristic_prune : generate BMC heuristic to generate a pruned encoding
  --bmc_heuristic_prune_deep : generate BMC heuristic to generate a pruned encoding (including continuous variables)
  --path : specify the path (ex: "[1,2,1,2,1]" to focus (Default: none)
  --new_format : parse file using the new file format
  -help  Display this list of options
  --help  Display this list of options
SMT: bouncing_ball_0_0.smt2, PATH : (set-logic
At line 1: syntax error, unexpected $end, expecting '('
/usr0/home/soonhok/work/dreal3/bin/bmc: Path QF_NRA_ODE) is not well-formed.
Usage: main.native [<options>] <.drh>
<options> are:
  -k : number of unrolling (Default: 3)
  --pathgen : generate paths
  --bmc_heuristic : generate BMC heuristic for dReal
  --bmc_heuristic_prune : generate BMC heuristic to generate a pruned encoding
  --bmc_heuristic_prune_deep : generate BMC heuristic to generate a pruned encoding (including continuous variables)
  --path : specify the path (ex: "[1,2,1,2,1]" to focus (Default: none)
  --new_format : parse file using the new file format
  -help  Display this list of options
  --help  Display this list of options
SMT: bouncing_ball_0_1.smt2, PATH : QF_NRA_ODE)
At line 1: syntax error, unexpected $end, expecting '('
/usr0/home/soonhok/work/dreal3/bin/bmc: Path (declare-fun is not well-formed.
Usage: main.native [<options>] <.drh>
<options> are:
  -k : number of unrolling (Default: 3)
  --pathgen : generate paths
  --bmc_heuristic : generate BMC heuristic for dReal
...
```

It should generate something like the following:
```
$ make
../../../bin/dReach -k 3 bouncing_ball.drh --precision=0.01 --ode_grid=1024 --visualize
dReal Options: --precision=0.01 --ode_grid=1024 --visualize
For k = 0, there is no feasible path to check.
SMT: bouncing_ball_1_0.smt2, PATH : [1,2]
Solution:
mode_0 : [1, 2] = [1, 1]
mode_1 : [1, 2] = [2, 2]
time_0 : [0, 10] = [1.428571427240968, 1.428571436554193]
time_1 : [0, 10] = [0.07330934476591829, 0.07330988900121173]
v_0_0 : [-100, 100] = [-0, 0]
v_0_t : [-100, 100] = [-14.0000000782311, -13.99999998696148]
v_1_0 : [-100, 100] = [13.99994659423828, 14.00004005432129]
v_1_t : [-100, 100] = [13.28150614306487, 13.28160986914408]
x_0_0 : [0, 20] = [10, 10]
x_0_t : [0, 20] = [0, 0]
x_1_0 : [0, 20] = [0, 0]
x_1_t : [0, 20] = [1, 1]
delta-sat with delta = 0.01000000000000000
For k = 1, dReach tried 1 feasible paths, all of them are unsat.
For k = 2, there is no feasible path to check.
SMT: bouncing_ball_3_0.smt2, PATH : [1,2,1,2]
Solution:
mode_0 : [1, 2] = [1, 1]
mode_1 : [1, 2] = [2, 2]
mode_2 : [1, 2] = [1, 1]
mode_3 : [1, 2] = [2, 2]
time_0 : [0, 10] = [1.428571428571423, 1.428571428571432]
time_1 : [0, 10] = [1.428571428568825, 1.428571428577926]
time_2 : [0, 10] = [1.428571400240486, 1.428571474987734]
time_3 : [0, 10] = [0.07330851375486458, 0.07331062879347541]
v_0_0 : [-100, 100] = [-0, 0]
v_0_t : [-100, 100] = [-14.00000000000004, -13.99999999999995]
v_1_0 : [-100, 100] = [13.99999999997453, 14.00000000006367]
v_1_t : [-100, 100] = [-0, 0]
v_2_0 : [-100, 100] = [-0, 0]
v_2_t : [-100, 100] = [-14.0000004548798, -13.99999972235676]
v_3_0 : [-100, 100] = [13.99981585907517, 14.0001909108687]
v_3_t : [-100, 100] = [13.28136519740505, 13.2817682134086]
x_0_0 : [0, 20] = [10, 10]
x_0_t : [0, 20] = [0, 0]
x_1_0 : [0, 20] = [0, 0]
x_1_t : [0, 20] = [9.999999999899773, 10.0000000001548]
x_2_0 : [0, 20] = [9.9999999159967, 10.00000017713556]
x_2_t : [0, 20] = [0, 0]
x_3_0 : [0, 20] = [0, 0]
x_3_t : [0, 20] = [1, 1]
delta-sat with delta = 0.01000000000000000
For k = 3, dReach tried 1 feasible paths, all of them are unsat.
```

**Comment by soonhokong** [comment]
I'll revert those commits. Please take your time to fix the problem and make another pull-request.

**Comment by danbryce** [comment]
I know.  Sorry.  Back them out and I’ll try again.

**Pull request closed without merging**
