### PR TITLE
Fix dylib build

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Fix a small "oops" from #317. Refactor the logic that creates the .dylib (on macOS) so that it actually works (the old approach was missing critical `-L` flags). Also, avoid unnecessary repetition by reusing logic better.

---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal3/321)

### CODE REVIEW

**Comment by soonho-tri** [comment]
I have:

```
$ ninja
[1/52] Linking CXX shared library lib/libdreal.dylib
FAILED: lib/libdreal.dylib
: && /Users/soonhok/bin/ccache-apple-clang++  -Wall -Wextra -Wno-deprecated-register -mfpmath=sse -msse -msse2 -g -DDREAL_DEBUG -DDREAL_TRACE -fno-inline  -dynamiclib -Wl,-headerpad_max_install_names -Wl,--no-undefined -Wl,-all_load -L/Users/soonhok/work/dreal3/build/debug-system-clang-shared/lib -o lib/libdreal.dylib -install_name @rpath/libdreal.dylib   lib/libdreal.a -libex -lcapd -ladept -lnlopt -lglpk -lprim -lpicosat -lm && :
ld: unknown option: --no-undefined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by soonho-tri** [comment]
My clang version:
```
$ /Users/soonhok/bin/ccache-apple-clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by soonho-tri** [comment]
Just in case, I'm cleaning the build directory and re-building things from scratch..

**Comment by mwoehlke-kitware** [comment]
On Apple, it's `-Wl,-undefined -Wl,error`. (For this purpose, though, it should be safe to skip that.)

**Pull request merged**
