### PR TITLE
Mcts

### PR DESCRIPTION
**Pull request by danbryce**
This branch includes support for Monte Carlo Tree search in ICP using the "--mcts" flag.  

The algorithm is based on MCTS whereby node/box expansions are bisections (2 children per parent) and rollouts for each node are based upon selecting a uniformly random value in each interval (where applicable).  The algorithm proceeds to expand nodes until it can find a simulation that results in "sat" (not delta-sat) box.  SAT is in quotes because the intervals may not represent a point, but they cannot be further bisected.  I'm looking for feedback on how to proceed.  My current thought is to pick either the lower or upper bound and propagate that.  

For example, I get the output for the attached smt2 (see func_fuellevel_gen_1_t):

```
Solution:
duration_generate__gen_1 : [0, 1000] = [1000, 1000]
func_capacity_gen_0_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_0_t : [-2000, 2000] = [1600, 1600]
func_capacity_gen_1_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_1_t : [-2000, 2000] = [1600, 1600]
func_capacity_gen_2_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_2_t : [-2000, 2000] = [1600, 1600]
func_fuellevel_gen_0_0 : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_0_t : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_1_0 : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_1_t : [-2000, 2000] = [-0, 2.273736754432321e-13]
func_fuellevel_gen_2_0 : [-2000, 2000] = [-0, 2.273736754432321e-13]
func_fuellevel_gen_2_t : [-2000, 2000] = [-0, 2.273736754432321e-13]
gamma_generate__gen_1_0 : [0, 1] = [1, 1]
gamma_generate__gen_1_t : [0, 1] = [1, 1]
time_0 : [0, 1000] = [429.0245871048094, 429.0245871048096]
time_1 : [0, 1000] = [999.9999999999998, 1000]
time_2 : [0, 1000] = [479.0878791489318, 479.0878791489318]
time_happening_0 : [0, 2000] = [0, 0]
time_happening_1 : [0, 2000] = [429.0245871048094, 429.0245871048096]
time_happening_2 : [0, 2000] = [1429.024587104809, 1429.02458710481]
time_happening_3 : [0, 2000] = [1908.112466253741, 1908.112466253741]
fact_refueling_gen_0 : Bool = false
fact_generator_ran_0 : Bool = false
fact_refueling_gen_1 : Bool = false
fact_generator_ran_1 : Bool = false
fact_refueling_gen_2 : Bool = false
fact_generator_ran_2 : Bool = true
duract_start_generate__gen_1 : Bool = true
duract_end_generate__gen_2 : Bool = true
delta-sat with delta = 0.00100000000000000
```
  
```
(set-logic QF_NRA_ODE)
(declare-fun fact_refueling_gen_0 () Bool)
(declare-fun fact_generator_ran_0 () Bool)
(declare-fun fact_refueling_gen_1 () Bool)
(declare-fun fact_generator_ran_1 () Bool)
(declare-fun fact_refueling_gen_2 () Bool)
(declare-fun fact_generator_ran_2 () Bool)
(declare-fun time_happening () Real [0, 2000])
(declare-fun time_0 () Real [0, 1000])
(declare-fun time_happening_0 () Real [0, 2000])
(declare-fun time_1 () Real [0, 1000])
(declare-fun time_happening_1 () Real [0, 2000])
(declare-fun time_2 () Real [0, 1000])
(declare-fun time_happening_2 () Real [0, 2000])
(declare-fun time_happening_3 () Real [0, 2000])
(declare-fun duration_generate__gen_1 () Real [0, 1000])
(declare-fun duract_start_generate__gen_1 () Bool)
(declare-fun duract_end_generate__gen_2 () Bool)
(declare-fun func_fuellevel_gen_0_0 () Real [-2000, 2000])
(declare-fun func_fuellevel_gen_0_t () Real [-2000, 2000])
(declare-fun func_capacity_gen_0_0 () Real [-2000, 2000])
(declare-fun func_capacity_gen_0_t () Real [-2000, 2000])
(declare-fun func_fuellevel_gen_1_0 () Real [-2000, 2000])
(declare-fun func_fuellevel_gen_1_t () Real [-2000, 2000])
(declare-fun func_capacity_gen_1_0 () Real [-2000, 2000])
(declare-fun func_capacity_gen_1_t () Real [-2000, 2000])
(declare-fun func_fuellevel_gen_2_0 () Real [-2000, 2000])
(declare-fun func_fuellevel_gen_2_t () Real [-2000, 2000])
(declare-fun func_fuellevel_gen () Real [-2000, 2000])
(declare-fun func_capacity_gen_2_0 () Real [-2000, 2000])
(declare-fun func_capacity_gen_2_t () Real [-2000, 2000])
(declare-fun func_capacity_gen () Real [-2000, 2000])
(declare-fun gamma_generate__gen_1_0 () Real [0, 1])
(declare-fun gamma_generate__gen_1_t () Real [0, 1])
(declare-fun gamma_generate__gen () Real [0, 1])
(define-ode flow_0 ((= d/dt[time_happening] 1)(= d/dt[func_fuellevel_gen] (+ 0 ))(= d/dt[func_capacity_gen] 0)))
(define-ode flow_1 ((= d/dt[time_happening] 1)(= d/dt[func_fuellevel_gen] (+ 0 (* gamma_generate__gen (* -1.0 1)) ))(= d/dt[func_capacity_gen] 0)(= d/dt[gamma_generate__gen] 0)))
(define-ode flow_2 ((= d/dt[time_happening] 1)(= d/dt[func_fuellevel_gen] (+ 0 ))(= d/dt[func_capacity_gen] 0)))
(assert (and (not fact_generator_ran_0) (not fact_refueling_gen_0) (= func_fuellevel_gen_0_0 1000)(= func_capacity_gen_0_0 1600)(= time_happening_0 0)(=> (not duract_start_generate__gen_1) (= duration_generate__gen_1 0))(=> duract_start_generate__gen_1 (= duration_generate__gen_1 1000))(=> (and duract_start_generate__gen_1 duract_end_generate__gen_2 ) (= (- time_happening_2 time_happening_1) (duration_generate__gen_1)))(=> (or duract_start_generate__gen_1 ) (and (forall_t 1 [0  time_1] (>= func_fuellevel_gen_1_t 0))))(=> (not (or duract_start_generate__gen_1 )) (= (gamma_generate__gen_1_0) 0))(=>  (= (gamma_generate__gen_1_0) 0) (not (or duract_start_generate__gen_1 )))(=> (or duract_start_generate__gen_1 ) (= (gamma_generate__gen_1_0) 1))(=>  (= (gamma_generate__gen_1_0) 1) (or duract_start_generate__gen_1 ))(=> duract_start_generate__gen_1 (or  duract_end_generate__gen_2))(=> duract_end_generate__gen_2 fact_generator_ran_2)(=> duract_end_generate__gen_2 (or  duract_start_generate__gen_1))(= func_fuellevel_gen_1_0 (+ func_fuellevel_gen_0_t ))(= func_capacity_gen_1_0 (+ func_capacity_gen_0_t ))(= func_fuellevel_gen_2_0 (+ func_fuellevel_gen_1_t ))(= func_capacity_gen_2_0 (+ func_capacity_gen_1_t ))(= [time_happening_1 func_fuellevel_gen_0_t func_capacity_gen_0_t ] (integral 0. time_0 [time_happening_0 func_fuellevel_gen_0_0 func_capacity_gen_0_0 ] flow_0))(= [time_happening_2 func_fuellevel_gen_1_t func_capacity_gen_1_t gamma_generate__gen_1_t ] (integral 0. time_1 [time_happening_1 func_fuellevel_gen_1_0 func_capacity_gen_1_0 gamma_generate__gen_1_0 ] flow_1))(= [time_happening_3 func_fuellevel_gen_2_t func_capacity_gen_2_t ] (integral 0. time_2 [time_happening_2 func_fuellevel_gen_2_0 func_capacity_gen_2_0 ] flow_2))(=> fact_generator_ran_0 fact_generator_ran_1)(=> (not fact_generator_ran_0) (not fact_generator_ran_1))(=> fact_refueling_gen_0 fact_refueling_gen_1)(=> (not fact_refueling_gen_0) (not fact_refueling_gen_1))(=> fact_generator_ran_1 fact_generator_ran_2)(=> (not (or duract_end_generate__gen_2 ))(=> (not fact_generator_ran_1) (not fact_generator_ran_2)))(=> fact_refueling_gen_1 fact_refueling_gen_2)(=> (not fact_refueling_gen_1) (not fact_refueling_gen_2))(<= (+ time_happening_0 0)time_happening_1)(= (+ time_happening_0 time_0)time_happening_1)(<= (+ time_happening_1 0)time_happening_2)(= (+ time_happening_1 time_1)time_happening_2) (= time_happening_3 (+ time_happening_2 time_2))))
(assert (and fact_generator_ran_2))
(check-sat)
(exit)
```

---
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal3/296)

### CODE REVIEW

**Comment by scungao** [comment]
Great!!! Have time to talk this afternoon? Ping me on skype.

**Comment by danbryce** [comment]
Yes.  I’m open today aside from school pickup for my son.

**Comment by danbryce** [comment]
FYI I fixed the non-bisectable interval issue by trying the lb and ub anyway.  Now I get a point:

```
duration_generate__gen_1 : [0, 1000] = [1000, 1000]
func_capacity_gen_0_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_0_t : [-2000, 2000] = [1600, 1600]
func_capacity_gen_1_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_1_t : [-2000, 2000] = [1600, 1600]
func_capacity_gen_2_0 : [-2000, 2000] = [1600, 1600]
func_capacity_gen_2_t : [-2000, 2000] = [1600, 1600]
func_fuellevel_gen_0_0 : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_0_t : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_1_0 : [-2000, 2000] = [1000, 1000]
func_fuellevel_gen_1_t : [-2000, 2000] = [-0, 0]
func_fuellevel_gen_2_0 : [-2000, 2000] = [-0, 0]
func_fuellevel_gen_2_t : [-2000, 2000] = [-0, 0]
gamma_generate__gen_1_0 : [0, 1] = [1, 1]
gamma_generate__gen_1_t : [0, 1] = [1, 1]
time_0 : [0, 1000] = [263.926798802444, 263.926798802444]
time_1 : [0, 1000] = [1000, 1000]
time_2 : [0, 1000] = [355.0089408661129, 355.0089408661129]
time_happening_0 : [0, 2000] = [0, 0]
time_happening_1 : [0, 2000] = [263.926798802444, 263.926798802444]
time_happening_2 : [0, 2000] = [1263.926798802444, 1263.926798802444]
time_happening_3 : [0, 2000] = [1618.935739668557, 1618.935739668557]
fact_refueling_gen_0 : Bool = false
fact_generator_ran_0 : Bool = false
fact_refueling_gen_1 : Bool = false
fact_generator_ran_1 : Bool = false
fact_refueling_gen_2 : Bool = false
fact_generator_ran_2 : Bool = true
duract_start_generate__gen_1 : Bool = true
duract_end_generate__gen_2 : Bool = true
```

**Comment by soonho-tri** [comment]
Reviewed 4 of 12 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dreal/dreal3/296)*

**Comment by soonho-tri** [comment]
Merged.

**Comment by soonho-tri** [comment]
Please run `make format` (see e02f6954a2c62b234e433b71aa7c2ffc4ad2027f). I fixed some function signatures (see a092d5b8acfc27a878a76eab543306165bbc3720).

**Comment by soonho-tri** [comment]
Also, if you want to add tests for `--mcts` option, do something like https://github.com/dreal/dreal3/blob/master/src/tests/nra/CMakeLists.txt#L119-L125.

**Pull request closed without merging**
