### PR TITLE
more methods in api

### PR DESCRIPTION
**Pull request by scungao**

### CODE REVIEW

**Comment by soonhokong** [comment]
what's "weird result in example"?

**Comment by scungao** [comment]
No problem there anymore.

**Comment by soonhokong** [comment]
OK. I'll take a closer look at them and possibly change the commit messages then :-)

**Comment by soonhokong** [comment]
Closed by 6c8e624ff6df453e8ed3b45d92195709389052c3.

**Comment by soonhokong** [comment]
@scungao: It seems that something is wrong here. I ran `./tests/cpp_api/cpp_api_example` and it failed to pass three tests:

```
-------------------------------------------------------------------------------
basic1
-------------------------------------------------------------------------------
/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:34
...............................................................................

/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:44: FAILED:
  REQUIRE( s.check() )
with expansion:
  false

-------------------------------------------------------------------------------
basic2
-------------------------------------------------------------------------------
/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:47
...............................................................................

/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:61: FAILED:
  REQUIRE( s.check() )
with expansion:
  false

(= (+ (+ x x) x) 0)
-------------------------------------------------------------------------------
basic3
-------------------------------------------------------------------------------
/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:64
...............................................................................

/Users/soonhok/work/dreal3/src/tests/cpp_api/example.cpp:70: FAILED:
  REQUIRE( s.check() )
with expansion:
  false

===============================================================================
test cases: 11 | 8 passed | 3 failed
assertions: 12 | 9 passed | 3 failed
```

**Comment by soonhokong** [comment]
Later, I'll add some code for `expr` class so that you can use `unordered_set<expr>` instead of `set<expr>`.

**Pull request closed without merging**
