### PR TITLE
Support for Networks of automata in dReach and heuristics in dReal

### PR DESCRIPTION
**Pull request by danbryce**
This change is [Reviewable](https://reviewable.io/reviews/dreal/dreal3/238)

### CODE REVIEW

**Comment by soonhokong** [comment]
Thanks, @danbryce.

I get a compilation error when I try clang on OSX (clang-3.6.2) and Ubuntu (clang-3.9.0). I get the following error message:

```
/usr0/home/soonhok/work/dreal3/src/opensmt/heuristics/hybrid_heuristic.cpp:174:22: error: use of overloaded operator '==' is ambiguous (with operand types 'value_type' (aka 'nlohmann::basic_json<std::map, std::vector, std::basic_string<char>, bool, long, double, std::allocator>') and 'int')
     if(adj_trans[2] == 1){
        ~~~~~~~~~~~~ ^  ~
/usr0/home/soonhok/work/dreal3/build/release-clang/include/json/json.hpp:1863:17: note: candidate function
    friend bool operator==(const_reference lhs, const_reference rhs) noexcept
                ^
/usr0/home/soonhok/work/dreal3/src/opensmt/heuristics/hybrid_heuristic.cpp:174:22: note: built-in candidate operator==(unsigned long long, int)
     if(adj_trans[2] == 1){
```

Could you check this?

**Comment by danbryce** [comment]
I think that I fixed the issue.  I’m using gcc5.2 and didn’t see the issue there.  I believe that clang is more picky about comparing longs to ints.

**Comment by soonhokong** [comment]
@danbryce, I still had a problem. I found that the following fixes the problem:

```
      if(adj_trans[2].get<int>() == 1){
```

Could you update `danbryce:dan-heuristics-pr`? I'll merge the PR then.

**Comment by soonhokong** [comment]
@danbryce, I merged the commits except 99dd332. I found that 99dd332 changes output smt2 files. Here is an example with `src/tests/drh/bouncing_ball.drh`:

Before:

```
(set-logic QF_NRA_ODE)
(declare-fun x () Real [0.000000, 20.000000])
(declare-fun v () Real [-100.000000, 100.000000])
(declare-fun x_0_0 () Real [0.000000, 20.000000])
(declare-fun x_0_t () Real [0.000000, 20.000000])
(declare-fun x_1_0 () Real [0.000000, 20.000000])
(declare-fun x_1_t () Real [0.000000, 20.000000])
(declare-fun x_2_0 () Real [0.000000, 20.000000])
(declare-fun x_2_t () Real [0.000000, 20.000000])
(declare-fun x_3_0 () Real [0.000000, 20.000000])
(declare-fun x_3_t () Real [0.000000, 20.000000])
(declare-fun v_0_0 () Real [-100.000000, 100.000000])
(declare-fun v_0_t () Real [-100.000000, 100.000000])
(declare-fun v_1_0 () Real [-100.000000, 100.000000])
(declare-fun v_1_t () Real [-100.000000, 100.000000])
(declare-fun v_2_0 () Real [-100.000000, 100.000000])
(declare-fun v_2_t () Real [-100.000000, 100.000000])
(declare-fun v_3_0 () Real [-100.000000, 100.000000])
(declare-fun v_3_t () Real [-100.000000, 100.000000])
(declare-fun time_0 () Real [0.000000, 10.000000])
(declare-fun time_1 () Real [0.000000, 10.000000])
(declare-fun time_2 () Real [0.000000, 10.000000])
(declare-fun time_3 () Real [0.000000, 10.000000])
(declare-fun mode_0 () Real [1.000000, 2.000000])
(declare-fun mode_1 () Real [1.000000, 2.000000])
(declare-fun mode_2 () Real [1.000000, 2.000000])
(declare-fun mode_3 () Real [1.000000, 2.000000])
(define-ode flow_1 ((= d/dt[v] -9.8) (= d/dt[x] v)))
(define-ode flow_2 ((= d/dt[v] -9.8) (= d/dt[x] v)))
(assert (and (or (and (= v_3_t (+ v_3_0 (* -9.8 time_3))) (= [v_3_t x_3_t] (integral 0. time_3 [v_3_0 x_3_0] flow_2)) (= mode_3 2) (forall_t 2 [0 time_3] (>= v_3_t 0)) (>= v_3_t 0) (>= v_3_0 0) (forall_t 2 [0 time_3] (>= x_3_t 0)) (>= x_3_t 0) (>= x_3_0 0)) (and (= v_3_t (+ v_3_0 (* -9.8 time_3))) (= [v_3_t x_3_t] (integral 0. time_3 [v_3_0 x_3_0] flow_1)) (= mode_3 1) (forall_t 1 [0 time_3] (<= v_3_t 0)) (<= v_3_t 0) (<= v_3_0 0) (forall_t 1 [0 time_3] (>= x_3_t 0)) (>= x_3_t 0) (>= x_3_0 0))) (or (and (= v_2_t (+ v_2_0 (* -9.8 time_2))) (= [v_2_t x_2_t] (integral 0. time_2 [v_2_0 x_2_0] flow_2)) (= mode_2 2) (forall_t 2 [0 time_2] (>= v_2_t 0)) (>= v_2_t 0) (>= v_2_0 0) (forall_t 2 [0 time_2] (>= x_2_t 0)) (>= x_2_t 0) (>= x_2_0 0) (= mode_3 1) (= v_2_t 0) (= v_3_0 v_2_t) (= x_3_0 x_2_t)) (and (= v_2_t (+ v_2_0 (* -9.8 time_2))) (= [v_2_t x_2_t] (integral 0. time_2 [v_2_0 x_2_0] flow_1)) (= mode_2 1) (forall_t 1 [0 time_2] (<= v_2_t 0)) (<= v_2_t 0) (<= v_2_0 0) (forall_t 1 [0 time_2] (>= x_2_t 0)) (>= x_2_t 0) (>= x_2_0 0) (= mode_3 2) (= x_2_t 0) (= v_3_0 (- 0 v_2_t)) (= x_3_0 x_2_t))) (or (and (= v_1_t (+ v_1_0 (* -9.8 time_1))) (= [v_1_t x_1_t] (integral 0. time_1 [v_1_0 x_1_0] flow_2)) (= mode_1 2) (forall_t 2 [0 time_1] (>= v_1_t 0)) (>= v_1_t 0) (>= v_1_0 0) (forall_t 2 [0 time_1] (>= x_1_t 0)) (>= x_1_t 0) (>= x_1_0 0) (= mode_2 1) (= v_1_t 0) (= v_2_0 v_1_t) (= x_2_0 x_1_t)) (and (= v_1_t (+ v_1_0 (* -9.8 time_1))) (= [v_1_t x_1_t] (integral 0. time_1 [v_1_0 x_1_0] flow_1)) (= mode_1 1) (forall_t 1 [0 time_1] (<= v_1_t 0)) (<= v_1_t 0) (<= v_1_0 0) (forall_t 1 [0 time_1] (>= x_1_t 0)) (>= x_1_t 0) (>= x_1_0 0) (= mode_2 2) (= x_1_t 0) (= v_2_0 (- 0 v_1_t)) (= x_2_0 x_1_t))) (or (and (= v_0_t (+ v_0_0 (* -9.8 time_0))) (= [v_0_t x_0_t] (integral 0. time_0 [v_0_0 x_0_0] flow_2)) (= mode_0 2) (forall_t 2 [0 time_0] (>= v_0_t 0)) (>= v_0_t 0) (>= v_0_0 0) (forall_t 2 [0 time_0] (>= x_0_t 0)) (>= x_0_t 0) (>= x_0_0 0) (= mode_1 1) (= v_0_t 0) (= v_1_0 v_0_t) (= x_1_0 x_0_t)) (and (= v_0_t (+ v_0_0 (* -9.8 time_0))) (= [v_0_t x_0_t] (integral 0. time_0 [v_0_0 x_0_0] flow_1)) (= mode_0 1) (forall_t 1 [0 time_0] (<= v_0_t 0)) (<= v_0_t 0) (<= v_0_0 0) (forall_t 1 [0 time_0] (>= x_0_t 0)) (>= x_0_t 0) (>= x_0_0 0) (= mode_1 2) (= x_0_t 0) (= v_1_0 (- 0 v_0_t)) (= x_1_0 x_0_t))) (and (= v_0_0 0) (= x_0_0 10)) (= mode_0 1) (= mode_3 2) (>= v_3_t 1) (= x_3_t 1)))
(check-sat)
(exit)
```

AFTER
```
(set-logic QF_NRA_ODE)
(declare-fun v () Real [0.000000])
(declare-fun x () Real [0.000000])
(declare-fun v_0_0 () Real [-100.000000, 100.000000])
(declare-fun v_0_t () Real [-100.000000, 100.000000])
(declare-fun v_1_0 () Real [-100.000000, 100.000000])
(declare-fun v_1_t () Real [-100.000000, 100.000000])
(declare-fun v_2_0 () Real [-100.000000, 100.000000])
(declare-fun v_2_t () Real [-100.000000, 100.000000])
(declare-fun v_3_0 () Real [-100.000000, 100.000000])
(declare-fun v_3_t () Real [-100.000000, 100.000000])
(declare-fun x_0_0 () Real [0.000000, 20.000000])
(declare-fun x_0_t () Real [0.000000, 20.000000])
(declare-fun x_1_0 () Real [0.000000, 20.000000])
(declare-fun x_1_t () Real [0.000000, 20.000000])
(declare-fun x_2_0 () Real [0.000000, 20.000000])
(declare-fun x_2_t () Real [0.000000, 20.000000])
(declare-fun x_3_0 () Real [0.000000, 20.000000])
(declare-fun x_3_t () Real [0.000000, 20.000000])
(declare-fun time_0 () Real [0.000000, 10.000000])
(declare-fun time_1 () Real [0.000000, 10.000000])
(declare-fun time_2 () Real [0.000000, 10.000000])
(declare-fun time_3 () Real [0.000000, 10.000000])
(declare-fun mode_1_0 () Real [1.000000, 2.000000])
(declare-fun mode_1_1 () Real [1.000000, 2.000000])
(declare-fun mode_1_2 () Real [1.000000, 2.000000])
(declare-fun mode_1_3 () Real [1.000000, 2.000000])
(declare-fun gamma_singleton0_1 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_2 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_1_0_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_2_0_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_1_1_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_2_1_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_1_2_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_2_2_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_1_3_0 () Real [0.000000, 1.000000])
(declare-fun gamma_singleton0_2_3_0 () Real [0.000000, 1.000000])
(define-ode flow_0 ((= d/dt[v] (+ (* -9.8 gamma_singleton0_1) (* -9.8 gamma_singleton0_2))) (= d/dt[x] (+ (* v gamma_singleton0_1) (* v gamma_singleton0_2))) (= d/dt[gamma_singleton0_1] 0) (= d/dt[gamma_singleton0_2] 0)))
(define-ode flow_1 ((= d/dt[v] (+ (* -9.8 gamma_singleton0_1) (* -9.8 gamma_singleton0_2))) (= d/dt[x] (+ (* v gamma_singleton0_1) (* v gamma_singleton0_2))) (= d/dt[gamma_singleton0_1] 0) (= d/dt[gamma_singleton0_2] 0)))
(define-ode flow_2 ((= d/dt[v] (+ (* -9.8 gamma_singleton0_1) (* -9.8 gamma_singleton0_2))) (= d/dt[x] (+ (* v gamma_singleton0_1) (* v gamma_singleton0_2))) (= d/dt[gamma_singleton0_1] 0) (= d/dt[gamma_singleton0_2] 0)))
(define-ode flow_3 ((= d/dt[v] (+ (* -9.8 gamma_singleton0_1) (* -9.8 gamma_singleton0_2))) (= d/dt[x] (+ (* v gamma_singleton0_1) (* v gamma_singleton0_2))) (= d/dt[gamma_singleton0_1] 0) (= d/dt[gamma_singleton0_2] 0)))
(assert (<= -100 v_0_0))
(assert (<= v_0_0 100))
(assert (<= -100 v_0_t))
(assert (<= v_0_t 100))
(assert (<= -100 v_1_0))
(assert (<= v_1_0 100))
(assert (<= -100 v_1_t))
(assert (<= v_1_t 100))
(assert (<= -100 v_2_0))
(assert (<= v_2_0 100))
(assert (<= -100 v_2_t))
(assert (<= v_2_t 100))
(assert (<= -100 v_3_0))
(assert (<= v_3_0 100))
(assert (<= -100 v_3_t))
(assert (<= v_3_t 100))
(assert (<= 0 x_0_0))
(assert (<= x_0_0 20))
(assert (<= 0 x_0_t))
(assert (<= x_0_t 20))
(assert (<= 0 x_1_0))
(assert (<= x_1_0 20))
(assert (<= 0 x_1_t))
(assert (<= x_1_t 20))
(assert (<= 0 x_2_0))
(assert (<= x_2_0 20))
(assert (<= 0 x_2_t))
(assert (<= x_2_t 20))
(assert (<= 0 x_3_0))
(assert (<= x_3_0 20))
(assert (<= 0 x_3_t))
(assert (<= x_3_t 20))
(assert (<= 0 time_0))
(assert (<= time_0 10))
(assert (<= 0 time_1))
(assert (<= time_1 10))
(assert (<= 0 time_2))
(assert (<= time_2 10))
(assert (<= 0 time_3))
(assert (<= time_3 10))
(assert (<= 1 mode_1_0))
(assert (<= mode_1_0 2))
(assert (<= 1 mode_1_1))
(assert (<= mode_1_1 2))
(assert (<= 1 mode_1_2))
(assert (<= mode_1_2 2))
(assert (<= 1 mode_1_3))
(assert (<= mode_1_3 2))
(assert (<= 0 gamma_singleton0_1_0_0))
(assert (<= gamma_singleton0_1_0_0 1))
(assert (<= 0 gamma_singleton0_2_0_0))
(assert (<= gamma_singleton0_2_0_0 1))
(assert (<= 0 gamma_singleton0_1_1_0))
(assert (<= gamma_singleton0_1_1_0 1))
(assert (<= 0 gamma_singleton0_2_1_0))
(assert (<= gamma_singleton0_2_1_0 1))
(assert (<= 0 gamma_singleton0_1_2_0))
(assert (<= gamma_singleton0_1_2_0 1))
(assert (<= 0 gamma_singleton0_2_2_0))
(assert (<= gamma_singleton0_2_2_0 1))
(assert (<= 0 gamma_singleton0_1_3_0))
(assert (<= gamma_singleton0_1_3_0 1))
(assert (<= 0 gamma_singleton0_2_3_0))
(assert (<= gamma_singleton0_2_3_0 1))
(assert (and (= mode_1_0 1) (= v_0_0 0) (= x_0_0 10)))
(assert (and (or (= mode_1_1 mode_1_0) (and (= v_0_t 0) (= v_1_0 v_0_t) (= x_1_0 x_0_t) (= mode_1_1 1) (= mode_1_0 2)) (and (= x_0_t 0) (= v_1_0 (- 0 v_0_t)) (= x_1_0 x_0_t) (= mode_1_1 2) (= mode_1_0 1))) (or (not (= mode_1_0 1)) (not (= mode_1_0 2))) (or (not (= mode_1_0 2)) (not (= mode_1_0 1))) (=> (= gamma_singleton0_1_0_0 0) (not (= mode_1_0 1))) (=> (not (= mode_1_0 1)) (= gamma_singleton0_1_0_0 0)) (=> (= gamma_singleton0_1_0_0 1) (= mode_1_0 1)) (=> (= mode_1_0 1) (= gamma_singleton0_1_0_0 1)) (=> (= gamma_singleton0_2_0_0 0) (not (= mode_1_0 2))) (=> (not (= mode_1_0 2)) (= gamma_singleton0_2_0_0 0)) (=> (= gamma_singleton0_2_0_0 1) (= mode_1_0 2)) (=> (= mode_1_0 2) (= gamma_singleton0_2_0_0 1)) (= [v_0_t x_0_t gamma_singleton0_1_0_0 gamma_singleton0_2_0_0] (integral 0. time_0 [v_0_0 x_0_0 gamma_singleton0_1_0_0 gamma_singleton0_2_0_0] flow_0)) (=> (= mode_1_0 2) (forall_t 0 [0 time_0] (and (>= x_0_t 0) (>= v_0_t 0)))) (=> (= mode_1_0 1) (forall_t 0 [0 time_0] (and (>= x_0_t 0) (<= v_0_t 0)))) (or (= x_0_t x_1_0) (and (= x_1_0 x_0_t) (= mode_1_1 1) (= mode_1_0 2)) (and (= x_1_0 x_0_t) (= mode_1_1 2) (= mode_1_0 1))) (or (= v_0_t v_1_0) (and (= v_1_0 v_0_t) (= mode_1_1 1) (= mode_1_0 2)) (and (= v_1_0 (- 0 v_0_t)) (= mode_1_1 2) (= mode_1_0 1))) (or (= mode_1_2 mode_1_1) (and (= v_1_t 0) (= v_2_0 v_1_t) (= x_2_0 x_1_t) (= mode_1_2 1) (= mode_1_1 2)) (and (= x_1_t 0) (= v_2_0 (- 0 v_1_t)) (= x_2_0 x_1_t) (= mode_1_2 2) (= mode_1_1 1))) (or (not (= mode_1_1 1)) (not (= mode_1_1 2))) (or (not (= mode_1_1 2)) (not (= mode_1_1 1))) (=> (= gamma_singleton0_1_1_0 0) (not (= mode_1_1 1))) (=> (not (= mode_1_1 1)) (= gamma_singleton0_1_1_0 0)) (=> (= gamma_singleton0_1_1_0 1) (= mode_1_1 1)) (=> (= mode_1_1 1) (= gamma_singleton0_1_1_0 1)) (=> (= gamma_singleton0_2_1_0 0) (not (= mode_1_1 2))) (=> (not (= mode_1_1 2)) (= gamma_singleton0_2_1_0 0)) (=> (= gamma_singleton0_2_1_0 1) (= mode_1_1 2)) (=> (= mode_1_1 2) (= gamma_singleton0_2_1_0 1)) (= [v_1_t x_1_t gamma_singleton0_1_1_0 gamma_singleton0_2_1_0] (integral 0. time_1 [v_1_0 x_1_0 gamma_singleton0_1_1_0 gamma_singleton0_2_1_0] flow_1)) (=> (= mode_1_1 2) (forall_t 1 [0 time_1] (and (>= x_1_t 0) (>= v_1_t 0)))) (=> (= mode_1_1 1) (forall_t 1 [0 time_1] (and (>= x_1_t 0) (<= v_1_t 0)))) (or (= x_1_t x_2_0) (and (= x_2_0 x_1_t) (= mode_1_2 1) (= mode_1_1 2)) (and (= x_2_0 x_1_t) (= mode_1_2 2) (= mode_1_1 1))) (or (= v_1_t v_2_0) (and (= v_2_0 v_1_t) (= mode_1_2 1) (= mode_1_1 2)) (and (= v_2_0 (- 0 v_1_t)) (= mode_1_2 2) (= mode_1_1 1))) (or (= mode_1_3 mode_1_2) (and (= v_2_t 0) (= v_3_0 v_2_t) (= x_3_0 x_2_t) (= mode_1_3 1) (= mode_1_2 2)) (and (= x_2_t 0) (= v_3_0 (- 0 v_2_t)) (= x_3_0 x_2_t) (= mode_1_3 2) (= mode_1_2 1))) (or (not (= mode_1_2 1)) (not (= mode_1_2 2))) (or (not (= mode_1_2 2)) (not (= mode_1_2 1))) (=> (= gamma_singleton0_1_2_0 0) (not (= mode_1_2 1))) (=> (not (= mode_1_2 1)) (= gamma_singleton0_1_2_0 0)) (=> (= gamma_singleton0_1_2_0 1) (= mode_1_2 1)) (=> (= mode_1_2 1) (= gamma_singleton0_1_2_0 1)) (=> (= gamma_singleton0_2_2_0 0) (not (= mode_1_2 2))) (=> (not (= mode_1_2 2)) (= gamma_singleton0_2_2_0 0)) (=> (= gamma_singleton0_2_2_0 1) (= mode_1_2 2)) (=> (= mode_1_2 2) (= gamma_singleton0_2_2_0 1)) (= [v_2_t x_2_t gamma_singleton0_1_2_0 gamma_singleton0_2_2_0] (integral 0. time_2 [v_2_0 x_2_0 gamma_singleton0_1_2_0 gamma_singleton0_2_2_0] flow_2)) (=> (= mode_1_2 2) (forall_t 2 [0 time_2] (and (>= x_2_t 0) (>= v_2_t 0)))) (=> (= mode_1_2 1) (forall_t 2 [0 time_2] (and (>= x_2_t 0) (<= v_2_t 0)))) (or (= x_2_t x_3_0) (and (= x_3_0 x_2_t) (= mode_1_3 1) (= mode_1_2 2)) (and (= x_3_0 x_2_t) (= mode_1_3 2) (= mode_1_2 1))) (or (= v_2_t v_3_0) (and (= v_3_0 v_2_t) (= mode_1_3 1) (= mode_1_2 2)) (and (= v_3_0 (- 0 v_2_t)) (= mode_1_3 2) (= mode_1_2 1)))))
(assert (and (=> (= gamma_singleton0_1_3_0 0) (not (= mode_1_3 1))) (=> (not (= mode_1_3 1)) (= gamma_singleton0_1_3_0 0)) (=> (= gamma_singleton0_1_3_0 1) (= mode_1_3 1)) (=> (= mode_1_3 1) (= gamma_singleton0_1_3_0 1)) (=> (= gamma_singleton0_2_3_0 0) (not (= mode_1_3 2))) (=> (not (= mode_1_3 2)) (= gamma_singleton0_2_3_0 0)) (=> (= gamma_singleton0_2_3_0 1) (= mode_1_3 2)) (=> (= mode_1_3 2) (= gamma_singleton0_2_3_0 1)) (= [v_3_t x_3_t gamma_singleton0_1_3_0 gamma_singleton0_2_3_0] (integral 0. time_3 [v_3_0 x_3_0 gamma_singleton0_1_3_0 gamma_singleton0_2_3_0] flow_3)) (=> (= mode_1_3 2) (forall_t 3 [0 time_3] (and (>= x_3_t 0) (>= v_3_t 0)))) (=> (= mode_1_3 1) (forall_t 3 [0 time_3] (and (>= x_3_t 0) (<= v_3_t 0))))))
(assert (and (= mode_1_3 2) (>= v_3_t 1) (= x_3_t 1) (or (not (= mode_1_3 1)) (not (= mode_1_3 2))) (or (not (= mode_1_3 2)) (not (= mode_1_3 1)))))
(check-sat)
(exit)
```

Here are some issues:

 - It introduces `gamma_singleton0_*` variables which do not appear in the original `drh` file. Could you add an option in BMC so that this is only enabled when the option is used?
 -  `(assert (<= -100 v_0_0))` and `(assert (<= v_0_0 100))` are redundant since we specify its domain in `(declare-fun v_0_0 () Real [-100.000000, 100.000000])`. I made [a commit](https://github.com/dreal/dreal3/commit/6b0f5e4460ecf78bdc06615df5db709f93dc3076) for this one. But it seems that your commit overwrites the change.

I've added a new branch [PR238](https://github.com/dreal/dreal3/tree/PR238), this branch is 1 commit ahead of `blessed/master`. When you resolve these issues, I'll merge the commit.

**Pull request closed without merging**
