### PR TITLE
Pr238

### PR DESCRIPTION
**Pull request by danbryce**
Hi Soonho,  I've refactored as you requested.

### CODE REVIEW

**Comment by soonhokong** [comment]
@danbryce, thanks! I'll do the review soon, and process the PR.

**Comment by soonhokong** [comment]
For the following files, the old version and the new version generate different `.smt2` files. It seems that you changed the flow numbering scheme? But I'm not sure that they mean the same formulas.

 - benchmarks/drh/glucose_control/fixed_parameters_varying_states.drh
 - benchmarks/drh/glucose_control/large_variance.drh
 - benchmarks/drh/glucose_control/small_variance.drh
 - benchmarks/drh/network/airplane/airplane-1-sat.drh
 - benchmarks/drh/network/airplane/airplane-1.drh
 - benchmarks/drh/network/airplane/airplane-sat.drh
 - benchmarks/drh/network/airplane/airplane.drh
 - benchmarks/drh/planning/battery/battery.drh
 - benchmarks/drh/planning/vehicle/vehicle.drh

Note that for the last one (benchmarks/drh/planning/vehicle/vehicle.drh), the new version only generates an exception `Uncaught exception: Not_found`.

**Comment by danbryce** [comment]
Hi, sorry, I”m just getting to this now.  The flow indices were previously based upon the mode id.  This is still the case, its just that we made a change to the mode ids themselves.  We extended the mode names to be strings and not integers.  However, there is still a unique index for each mode.  I believe that what you are seeing is the name and index of each mode no longer coincide.  For example, you may have a mode “1” that has an index 5.  

I am looking into the exception now.

**Comment by soonhokong** [comment]
closed by 3fd3121

**Pull request closed without merging**
