### PR TITLE
fix(icp/lp_icp): unsat instead of sat in lp_icp

### PR DESCRIPTION
**Pull request by dzufferey**
- fix unsat instead of sat in lp_icp
- added `--lp-icp-prune` option to use the LP to prune the variable on which we branch
- improve `is_linear` in glpk_wrapper

### CODE REVIEW

**Comment by soonhokong** [comment]
Closed by 50491e71e98b3b2f980f5f05340e206d7d175512

**Comment by soonhokong** [comment]
I've got some problems:

1. The following tests failed. They generated `unsat`s while `delta-sat`s are expected:

```
regression_nra_lp_icp_prune_osmosis-midair.smt2
regression_nra_lp_icp_prune_simdreal_4.smt2
regression_nra_lp_icp_prune_simdreal_5.smt2
regression_nra_lp_icp_prune_stephen_01.smt2
regression_nra_lp_icp_prune_tai_sin_03.smt2
```

2. I also have:

```
$ ./dReal ../../src/tests/nra/push_pop_02.smt2 --lp-icp-prune
dReal: /usr0/home/soonhok/work/dreal3/src/opensmt/tsolvers/THandler.C:172: bool THandler::assertLits(): Assertion `v <= 1 || e' failed.
[2]    17063 abort (core dumped)  ./dReal ../../src/tests/nra/push_pop_02.smt2 --lp-icp-prune
```

Backtrace from GDB:
```
#0  0x00007ffff6071035 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff607479b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6069e1e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6069ec2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000ababf1 in THandler::assertLits (this=0x61200000bec0) at /usr0/home/soonhok/work/dreal3/src/opensmt/tsolvers/THandler.C:172
#5  0x0000000000a2c0a4 in CoreSMTSolver::checkTheory (this=0x61a00001f280, complete=false) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/Theory.C:36
#6  0x00000000009fff78 in CoreSMTSolver::search (this=0x61a00001f280, nof_conflicts=110, nof_learnts=14) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/CoreSMTSolver.C:1820
#7  0x0000000000a02c74 in CoreSMTSolver::solve (this=0x61a00001f280, assumps=..., max_conflicts=0) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/CoreSMTSolver.C:2126
#8  0x0000000000a16036 in SimpSMTSolver::solve (this=0x61a00001f280, assumps=..., conflicts=0, do_simp=false, turn_off_simp=false) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.C:344
#9  0x0000000000a1595a in SimpSMTSolver::solve (this=0x61a00001f280, assumps=..., do_simp=true, turn_off_simp=false) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.C:215
#10 0x000000000096404f in SimpSMTSolver::solve (this=0x61a00001f280, do_simp=true, turn_off_simp=false) at /usr0/home/soonhok/work/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.h:223
#11 0x000000000095f3a5 in OpenSMTContext::CheckSAT (this=0x7fffffffd960) at /usr0/home/soonhok/work/dreal3/src/opensmt/api/OpenSMTContext.C:737
#12 0x000000000095b9c8 in OpenSMTContext::executeIncremental (this=0x7fffffffd960) at /usr0/home/soonhok/work/dreal3/src/opensmt/api/OpenSMTContext.C:272
#13 0x000000000095b3f9 in OpenSMTContext::executeCommands (this=0x7fffffffd960) at /usr0/home/soonhok/work/dreal3/src/opensmt/api/OpenSMTContext.C:212
#14 0x0000000000912e6b in main (argc=3, argv=0x7fffffffdc98) at /usr0/home/soonhok/work/dreal3/src/main.cpp:120
```

**Comment by dzufferey** [comment]
about `push_pop_02`, it was already failing before today's pull request. I remember there was a recent issue about push and pop. Could some changes there make a difference for the lp_icp ?

I'll check what is going on with the other tests.

**Comment by soonhokong** [comment]
@dzufferey, I see. I'll take care `push_pop_02` case.

**Comment by dzufferey** [comment]
With only `--lp-icp` the solutions are fine. However, some tests may fails due to the extra output from GLKP.

With `--lp-icp-prune`, there are some problems. The following tests fails (unsat instead of delta sat):
`stephen_01.smt2`
`simdreal_4.smt2`
`simdreal_5.smt2`
`osmosis-midair.smt2`
I need to check what is going on. I suspect that we cannot trust GLPK for pruning. With `--lp-icp`, the pruning ultimately depends on the contractors or the exact solver.
`--lp-icp-prune`, on the other hand, trusts GLPK for maximization and minimization. This is one optimization we discussed with @scungao. I need to check if it is possible to do something about that or if we should remove that option altogether.

**Comment by dzufferey** [comment]
My bad, actually there was a bug in `--lp-icp-prune`. the LP pruning was not handling correctly unbounded solutions. I created a pull request to fix that.
I did not have the time to try every test. That option is quick slow.

**Pull request closed without merging**
